run:
  timeout: 10m

linters:
  enable-all: true
  disable:
    - deadcode
    - paralleltest
    - testpackage
    - gofumpt
    - nlreturn
    - varnamelen
    - wsl
    - funlen
    - ireturn
    - unconvert
    - wrapcheck
    - ifshort
    - interfacer
    - exhaustivestruct
    - golint
    - structcheck