= Key Object

In PuzzleDB, records, schemas, and indices are all represented as key-value pairs. This section explains the format of the key object.

== Key Header Specification

The all key object has a header that reprents the key category, version and stored value type.  The key header is a 2-byte header that is prepended to every key in the key-value store. The key header is reserved as follows:

[format="csv", options="header, autowidth"]
|====
include::csv/kv-store-header.csv[]
|====

The key header begins with a 1-byte identifier for the key type, enabling key type-based searching. Duplication is tolerated because a value type is reserved for each key type.

== Key Categories

The key-value store is a collection of key-value records, where each record is a key-value pair, consisting of a header as the key. The key-value store supports the following categories of key-value records:

[format="csv", options="header, autowidth"]
|====
include::csv/kv-store-category.csv[]
|====

The combination of object and index element name and value is repeated by the index format.