#!/bin/bash
# Copyright (C) 2023 The PuzzleDB Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DATE=$(date '+%Y-%m-%d')
HOSTNAME=$(hostname)
VER=$(git tag | tail -n 1)
LOG_DIR="../../../../log"
LOG_FILE_NAME="${LOG_DIR}/pgbench-${VER}-${DATE}-${HOSTNAME}.log"

pgbench -i --init-steps=dtpg -h localhost pgbench
pgbench -c 1 -t 100 -h localhost pgbench > ${LOG_FILE_NAME}
