= Plug-In Services

PuzzleDB provides default plug-in services that include query, storage, and coordinator plug-ins and defines the default plug-in types as follows:

[format="csv", options="header, autowidth"]
|====
include::plugin/plugin-types.csv[]
|====

`Distributed`: Indicates whether the PuzzleDB instance node or plugin instance node supports a distributed operation. The non-distributed plug-ins are provided for stand-alone operation or for internal testing of PuzzleDB.

`Dependency`: Indicates other plugin types required to run the plugin.

== Plug-In Interfaces

PuzzleDB defines the core plug-in interfaces based on the following concepts.

=== Query Interface

PuzzleDB defines the query interface to support any database protocols such as Redis, MongoDB and MySQL protocols. The query interface is kept to a minimal specification in order to support a wide variety of database protocols.

=== Storage Interface

PuzzleDB defines the low level storage interface as an ordered key-value store like early Google Spannerr. PuzzleDB expects that the storage plug-in components are implemented based on ordered key-value stores like FoundationDB rather than non-orders hashing key-value stores like MongoDB and Cassandra. 

=== Coordinator Interface

PuzzleDB defines the coordinator interface to synchronize between PuzzleDB nodes. PuzzleDB expects that the coordinator components are implemented based on existing distributed coordinator services such as Apache ZooKeeper or etcd.
