# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set up golangci-lint
      run: sudo snap install golangci-lint

    - name: Set up FoundationDB
      run: |
         sudo wget https://github.com/apple/foundationdb/releases/download/6.3.25/foundationdb-clients_6.3.25-1_amd64.deb
         sudo dpkg -i foundationdb-clients_6.3.25-1_amd64.deb
         sudo wget https://github.com/apple/foundationdb/releases/download/6.3.25/foundationdb-server_6.3.25-1_amd64.deb
         sudo dpkg -i foundationdb-server_6.3.25-1_amd64.deb

    - name: Test
      run: make test
