# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'

    - name: Set up golangci-lint
      run: sudo snap install golangci-lint --classic

    - name: Set up FoundationDB
      run: |
         sudo wget --directory-prefix=/tmp https://github.com/apple/foundationdb/releases/download/7.3.17/foundationdb-clients_7.3.17-1_amd64.deb
         sudo apt install -y /tmp/foundationdb-clients_7.3.17-1_amd64.deb
         sudo wget --directory-prefix=/tmp https://github.com/apple/foundationdb/releases/download/7.3.17/foundationdb-server_7.3.17-1_amd64.deb
         sudo apt install -y /tmp/foundationdb-server_7.3.17-1_amd64.deb
         sudo service foundationdb start

    - name: Test
      run: CGO_ENABLED=1 make unittest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: puzzledb-cover.out
