# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Set up golangci-lint
      run: sudo snap install golangci-lint --classic

    - name: Set up FoundationDB
      run: |
         sudo wget --directory-prefix=/tmp https://github.com/apple/foundationdb/releases/download/7.3.67/foundationdb-clients_7.3.67-1_amd64.deb
         sudo apt install -y /tmp/foundationdb-clients_7.3.67-1_amd64.deb
         sudo wget --directory-prefix=/tmp https://github.com/apple/foundationdb/releases/download/7.3.67/foundationdb-server_7.3.67-1_amd64.deb
         sudo apt install -y /tmp/foundationdb-server_7.3.67-1_amd64.deb
         sudo service foundationdb start

    - name: Test
      run: |
          go get github.com/apple/foundationdb/bindings/go@63035b5c3ecb65a615126cf3d62e36df58a9c994
          go mod tidy
          CGO_ENABLED=1 make certs && make unittest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: puzzledb-cover.out
